### ISSUE TITLE
There are some different bettween this code and R package "compareC"

### ISSUE THREAD

**Issue by lgylylyct** [wjn0/compare_concordance#1]
Hi, wjn0.
Thanks for your code.

I used **this code** and **R package "compareC"** to process sample data, respectively. Then, I found that the two results were different. So I checked the code and found two errors.

In line 54 of [compare_concordance](https://github.com/wjn0/compare_concordance/tree/main/compare_concordance)/compare_concordance.py, `statusX = np.asarray(status).astype(int)` should be modified to `statusX = np.asarray(status).astype(np.int32)`, because `int` is equal to `np.int64`.

In line 83 of [compare_concordance](https://github.com/wjn0/compare_concordance/tree/main/compare_concordance)/compare_concordance.py, `_m = np.asarray([[cov_t1213, cov_t1113], [cov_t1112, var_t11]])` should be modified ify to `_m = np.asarray([[cov_t1213, cov_t1112], [cov_t1113, var_t11]])`.

In the **R package compareC**, the source code is `matrix(c(cov.t1213,cov.t1113,cov.t1112,var.t11),2)`, but the matrix is filled by columns in the default setting, so the final matrix is `[[t1213, t1112],[t1113, t11]]`

After the above modification, I got the same results.

**Comment by wjn0** [comment]
Thanks very much for the report! It looks like the `int` issue is platform dependent, but I think your proposed fix resolves it for all platforms. The latest commit on `develop` aims to resolve these two issues, and I'll push a fixed package to Pypi soon.
